name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: python -m pip install poetry
      - run: poetry install --only main
      - run: poetry run ruff .
      - run: poetry run black --check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: python -m pip install poetry
      - run: poetry install --with dev
      - run: poetry run pytest -q

  smoke:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: python -m pip install .
      - run: |
          echo -e "a,b\n1,2\n3,4" > smoke.csv
          dataprof profile smoke.csv --minimal --out smoke
      - run: ls smoke
