name: Publish Docs 📚

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # fetch gh-pages branch so we can push there
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies (docs)
        run: |
          python -m pip install poetry
          poetry install --no-interaction --with docs

      - name: Build Sphinx HTML
        run: |
          cd docs
          sphinx-build -b html source _build/html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          # optional: keep history of pages commits
          keep_history: true
