name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # needed to update the GitHub Release draft
      pull-requests: write   # needed if you aggregate PR metadata
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml
